api-version: 2019-12-01
location: westus3
name: APP_NAME
properties:
  containers:
  - name: streamlitapp
    properties:
      image: NAME_OF_REGISTRY.azurecr.io/azure_demo:v1
      ports:
      - port: 80
        protocol: TCP
      - port: 443
        protocol: TCP
      resources:
        requests:
          cpu: 2.0
          memoryInGB: 1.5
  imageRegistryCredentials:
  - server: NAME_OF_REGISTRY.azurecr.io
    username: NAME_OF_REGISTRY
    password: REDACTED
  restartPolicy: Never
  ipAddress:
    ports:
    - port: 443
      protocol: TCP
    - port: 80
      protocol: TCP
    type: Public
    dnsNameLabel: FQDN_NAME
  osType: Linux
tags: null
type: Microsoft.ContainerInstance/containerGroups